### PR TITLE
fix lwansbrough/react-native-google-analytics#14

### PR DESCRIPTION
**Pull request by deminoth**
fix for issue #14

### CODE REVIEW

**Comment by olitomas** [comment]
Great, was waiting for this fix. Can you merge this in to master ? :)

**Comment by lwansbrough** [comment]
Ahh, that was easy! :) I can push this to npm later today.

**Comment by olitomas** [comment]
Awesome! Thank you :+1:

**Comment by petrvojta** [comment]
:+1:

**Comment by lwansbrough** [comment]
Done. :)

**Pull request merged**
